In [1]:
import numpy as np
import scipy.io as si

In [2]:
data = si.loadmat('face_emotion_data.mat')

In [3]:
y = data['y']
X = data['X']

In [4]:
toInv = X.T @ X
inv = np.linalg.inv(toInv)
what = inv @ X.T @ y
what

array([[ 0.94366942],
       [ 0.21373778],
       [ 0.26641775],
       [-0.39221373],
       [-0.00538552],
       [-0.01764687],
       [-0.16632809],
       [-0.0822838 ],
       [-0.16644364]])

In [5]:
y9 = np.sign(X @ what)
numInc9 = 0
for i in range(len(y)):
    if y9[i] != y[i]:
        numInc9 += 1

perInc9 = numInc9 *100 / len(y)
perInc9

2.34375

In [6]:
nX = np.hstack((X[:,0].reshape(-1,1), X[:,2].reshape(-1,1), X[:,3].reshape(-1,1)))
nX.shape

(128, 3)

In [7]:
toInv2 = nX.T @ nX
inv2 = np.linalg.inv(toInv2)
what2 = inv2 @ nX.T @ y
what2

array([[ 0.70546316],
       [ 0.8737872 ],
       [-0.78805643]])

In [8]:
nY = np.sign(nX @ what2)

In [9]:
numInc = 0
for i in range(len(y)):
    if nY[i] != y[i]:
        numInc += 1

perInc = numInc *100 / len(y)
perInc

6.25

In [10]:
errRate = np.empty(8)
for i in range(0,8):
    toAdd = X[i*16:(i+1)*16 - 1]
    yToUse = y[i*16:(i+1)*16 - 1]

    train = X
    yTrain = y
    for j in range(0,16):
        train = np.delete(train, (i*16) + 15 - j, 0)
        yTrain = np.delete(yTrain, (i*16) + 15 - j, 0)
    
    classWeights = np.linalg.inv(train.T @ train) @ train.T @ yTrain


    test = toAdd
    yTest = yToUse
    numMissClass = 0
    for j in range(0,len(yTest)):
        if np.sign(test[j] @ classWeights) != yTest[j]:
            numMissClass += 1
    
    errRate[i] = numMissClass / 16


errRate

array([0.0625, 0.0625, 0.125 , 0.0625, 0.    , 0.0625, 0.    , 0.    ])

In [11]:
avgErrRate = np.mean(errRate)
avgErrRate

np.float64(0.046875)